openapi: 3.0.1
info:
  title: myapp
  description: call-router-api
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: Examples
  description: Simple example endpoints
- name: Specification
  description: The swagger API specification
paths:
  /examples/sendNotification:
    post:
      tags:
        - Examples
      responses:
        200:
          description: test push notification
          content: {}
  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
  /calls:
    get:
      tags:
        - Numbers
      parameters:
        - $ref: '#/components/parameters/authAccountSidParam'
        - $ref: '#/components/parameters/authTokenParam'
        - $ref: '#/components/parameters/pageTokenParam'
      responses:
        200:
          description: Returning all call logs with pagination
          content: {}
    post:
      tags:
        - Numbers
      responses:
        200:
          description: Call forwarding successfully created
          content: {}
  /calls/status-changed:
    post:
      tags:
        - Numbers
      responses:
        200:
          description: call status is changed for this incoming call
          content: {}
  /voip/twiml-app:
    post:
      summary: Create a new TwiML app and return the sid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newTwiMLAppPostBody'
      responses:
        200:
          description: newly created twiML app info
          content: {}
  /voip/twiml-app/response:
    post:
      summary: Get the TwiML fixture
      responses:
        200:
          description: TwiML fixture
          content: {}
  /voip/clientToken:
    get:
      summary: get a voip client token by api key
      parameters:
        - $ref: '#/components/parameters/authAccountSidParam'
        - $ref: '#/components/parameters/apiKeyParam'
        - $ref: '#/components/parameters/apiSecretParam'
        - $ref: '#/components/parameters/twiMlAppSidParam'
      responses:
        200:
          description: generated JWT
          content: {}
  /video/clientToken:
    get:
      summary: get a video client token by api key
      parameters:
        - $ref: '#/components/parameters/authAccountSidParam'
        - $ref: '#/components/parameters/apiKeyParam'
        - $ref: '#/components/parameters/apiSecretParam'
      responses:
        200:
          description: generated JWT
          content: {}
  /sms/message:
    get:
      summary: Returning all sms history with pagination
      tags:
        - sms
      parameters:
        - $ref: '#/components/parameters/authAccountSidParam'
        - $ref: '#/components/parameters/authTokenParam'
        - $ref: '#/components/parameters/pageTokenParam'
      responses:
        200:
          description: Returned all SMS history with pagination
          content: {}
    post:
      summary: create a new SMS messsage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/messageCreationPostBody'
      responses:
        200:
          description: Message created, returned new message
          content: {}
  /sms/message/{from}:
    get:
      summary: Returning all sms history with pagination
      tags:
        - sms
      parameters:
        - $ref: '#/components/parameters/authAccountSidParam'
        - $ref: '#/components/parameters/authTokenParam'
        - $ref: '#/components/parameters/fromSenderParam'
        - $ref: '#/components/parameters/toSenderParam'
        - $ref: '#/components/parameters/pageToken1Param'
        - $ref: '#/components/parameters/pageToken2Param'
      responses:
        200:
          description: Returned all SMS history with pagination for a specific from number
          content: {}
  /users/createApiKey:
    post:
      summary: Create a new API key and return the value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createApiKeyPostBody'
      responses:
        200:
          description: newly created api key info
          content: {}
  /users/allLocalNumbers:
    get:
      tags:
        - Users
      parameters:
        - $ref: '#/components/parameters/authAccountSidParam'
        - $ref: '#/components/parameters/authTokenParam'
      responses:
        200:
          description: Returning all local numbers belongs to this user
          content: {}
  /login:
    post:
      tags:
        - Login
      requestBody:
        description: auth request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginAuthPostBody'
      responses:
        204:
          description: success
        403:
          description: forbidden
components:
  parameters:
    authTokenParam:
      in: query
      name: accessToken
      schema:
        type: string
      required: true
    authAccountSidParam:
      in: query
      name: accountSid
      schema:
        type: string
      required: true
    apiKeyParam:
      in: query
      name: apiKey
      schema:
        type: string
      required: true
    apiSecretParam:
      in: query
      name: apiSecret
      schema:
        type: string
      required: true
    twiMlAppSidParam:
      in: query
      name: twiMlAppSid
      schema:
        type: string
      required: true
    pageTokenParam:
      in: query
      name: pageToken
      schema:
        type: string
      required: false
    pageToken1Param:
      in: query
      name: pageToken1
      schema:
        type: string
      required: false
    pageToken2Param:
      in: query
      name: pageToken2
      schema:
        type: string
      required: false
    fromSenderParam:
      in: path
      name: from
      schema:
        type: string
      required: true
    toSenderParam:
      in: query
      name: to
      schema:
        type: string
      required: false
  schemas:
    loginAuthPostBody:
      title: authBody
      required:
      - accountSid
      - accessToken
      properties:
        accountSid:
          type: string
        accessToken:
          type: string
    newTwiMLAppPostBody:
      title: twiMLBody
      required:
      - accountSid
      - accessToken
      properties:
        accountSid:
          type: string
        accessToken:
          type: string
    createApiKeyPostBody:
      title: apiKeyBody
      required:
      - accountSid
      - accessToken
      properties:
        accountSid:
          type: string
        accessToken:
          type: string
    messageCreationPostBody:
      title: message creation post body
      required:
      - accountSid
      - accessToken
      - messageBody
      - from
      - to
      properties:
        accountSid:
          type: string
        accessToken:
          type: string
        messageBody:
          type: string
        from:
          type: string
        to:
          type: string
