openapi: 3.0.1
info:
  title: myapp
  description: call-router-api
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: Examples
  description: Simple example endpoints
- name: Specification
  description: The swagger API specification
paths:
  /examples/sendNotification:
    post:
      tags:
        - Examples
      responses:
        200:
          description: test push notification
          content: {}
  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
  /calls:
    get:
      tags:
        - Numbers
      responses:
        200:
          description: Returning all call logs with pagination
          content: {}
    post:
      tags:
        - Numbers
      responses:
        200:
          description: Call forwarding successfully created
          content: {}
  /calls/status-changed:
    post:
      tags:
        - Numbers
      responses:
        200:
          description: call status is changed for this incoming call
          content: {}
  /users/allLocalNumbers:
    get:
      tags:
        - Users
      parameters:
        - in: query
          name: accountSid
          schema:
            type: string
          required: true
        - in: query
          name: accessToken
          schema:
            type: string
          required: true
      responses:
        200:
          description: Returning all local numbers belongs to this user
          content: {}
components:
  schemas:
    allActiveNumbers:
      title: numbers
      required:
      - accountSid
      - accessToken
      type: object
      properties:
        accountSid:
          type: string
        accessToken:
          type: string
